add mailing records addition
elementor/elementor-cloud-domain-connect-templates pull request #2
Opened 2022-07-17 07:20 UTC by asafdl

2022-07-18 07:29 UTC, yotamselementor commented on elementor.com.email.json
> +
```suggestion
```

2022-07-19 13:39 UTC, danielkatz requested changes

2022-07-19 13:39 UTC, danielkatz commented on elementor.com.email.json
> +{
The formatting is inconsistent

2022-07-19 13:48 UTC, danielkatz approved these changes

2022-07-19 13:49 UTC, merged